### ISSUE TITLE
Can't run "Easy Installers" on macOS

### ISSUE THREAD

**Issue by leolobato** [SilicaAndPina/psvimgtools-frontend#22]
I've cloned the repository, installed `bplistlib` and `requests`, extracted `psvimgtools-frontend-macos.zip` inside the cloned folder, created `cmadir.txt` and ran `python run.py`.

I was able to view the GUI, but when I click on "Easy Installers", I get the following error on terminal:

```
Exception in Tkinter callback
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk/Tkinter.py", line 1536, in __call__
    return self.func(*args)
  File "/PSVita/psvimgtools/psvimgtools-frontend/main_support.py", line 34, in esyInstall
    import easyInstallers
  File "/PSVita/psvimgtools/psvimgtools-frontend/easyInstallers.py", line 18, in <module>
    import easyInstallers_support
  File "/PSVita/psvimgtools/psvimgtools-frontend/easyInstallers_support.py", line 17, in <module>
    import easyinstallers.EmuBubble.main as emububble
ImportError: No module named EmuBubble.main
```

I'm running macOS 10.12.14.

**Comment by SilicaAndPina** [comment]
whats inside the "EmuBubble" folder?

**Comment by leolobato** [comment]
There's an `EmuBubble` folder inside `EasyInstallers`, but no `main.py` inside `EmuBubble`.

Here's the full tree: https://pastebin.com/gupTYcgw

**Comment by SilicaAndPina** [comment]
Seems i forgot to upload main.py to GIT. >_>
