### ISSUE TITLE
Can't run on Mac, Python issues? -Help!

### ISSUE THREAD

**Issue by Sir-Charles** [SilicaAndPina/psvimgtools-frontend#50]
**So I'm trying to run this on OSX Yosemite, Python 2.7 installed natively, but I also tried installing a newer 2.7 and 3.6. This is the first thing I see:**

~ Yosemite$ /Users/Yosemite/Downloads/psvimgtools-frontend-macos/run ; exit;
Error loading Python lib '/Users/Yosemite/Downloads/psvimgtools-frontend-macos/Python': dlopen(/Users/Yosemite/Downloads/psvimgtools-frontend-macos/Python, 10): no suitable image found.  Did find:
	/Users/Yosemite/Downloads/psvimgtools-frontend-macos/Python: code signature invalid for '/Users/Yosemite/Downloads/psvimgtools-frontend-macos/Python'

logout

**So then I try to do:**

sudo codesign -f -s - /Users/Yosemite/Downloads/psvimgtools-frontend-macos/Python

**and then I get:**

~ Yosemite$ /Users/Yosemite/Downloads/psvimgtools-frontend-macos/run ; exit;
mod is NULL - structTraceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/struct.py", line 1, in <module>
    from _struct import *
ImportError: dlopen(/Users/Yosemite/Downloads/psvimgtools-frontend-macos/_struct.so, 2): no suitable image found.  Did find:
	/Users/Yosemite/Downloads/psvimgtools-frontend-macos/_struct.so: code signature invalid for '/Users/Yosemite/Downloads/psvimgtools-frontend-macos/_struct.so'

mod is NULL - pyimod02_archiveTraceback (most recent call last):
  File "/Library/Python/2.7/site-packages/PyInstaller/loader/pyimod02_archive.py", line 28, in <module>
ImportError: No module named struct
mod is NULL - pyimod03_importersTraceback (most recent call last):
  File "/Library/Python/2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 24, in <module>
ImportError: No module named pyimod02_archive
Traceback (most recent call last):
  File "PyInstaller/loader/pyiboot01_bootstrap.py", line 15, in <module>
ImportError: No module named pyimod03_importers
Failed to execute script pyiboot01_bootstrap
logout

**So I codesign _struct.so and I try to install pyinstaller with "pip install pyinstaller" and I also go to github.com/pysinstaller/pyinstaller/ and get the "PyInstaller" folder to put in "/Library/Python/2.7/site-packages/" cause it wasn't there. and try run again:**

~ Yosemite$ /Users/Yosemite/Downloads/psvimgtools-frontend-macos/run ; exit;
mod is NULL - pyimod02_archiveTraceback (most recent call last):
  File "/Library/Python/2.7/site-packages/PyInstaller/loader/pyimod02_archive.py", line 30, in <module>
    import zlib
ImportError: dlopen(/Users/Yosemite/Downloads/psvimgtools-frontend-macos/zlib.so, 2): no suitable image found.  Did find:
	/Users/Yosemite/Downloads/psvimgtools-frontend-macos/zlib.so: code signature invalid for '/Users/Yosemite/Downloads/psvimgtools-frontend-macos/zlib.so'

mod is NULL - pyimod03_importersTraceback (most recent call last):
  File "/Library/Python/2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 24, in <module>
    from pyimod02_archive import ArchiveReadError, ZlibArchiveReader
ImportError: No module named pyimod02_archive
Traceback (most recent call last):
  File "PyInstaller/loader/pyiboot01_bootstrap.py", line 15, in <module>
ImportError: No module named pyimod03_importers
Failed to execute script pyiboot01_bootstrap
logout

**So I codesign zlib.so this time and run:**

~ Yosemite$ /Users/Yosemite/Downloads/psvimgtools-frontend-macos/run ; exit;
Traceback (most recent call last):
  File "run.py", line 1, in <module>
  File "/Library/Python/2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
    # executes the module code. This is crucial because the module
  File "defs.py", line 1, in <module>
  File "/Library/Python/2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
    # executes the module code. This is crucial because the module
  File "json/__init__.py", line 108, in <module>
  File "/Library/Python/2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
    # executes the module code. This is crucial because the module
  File "json/decoder.py", line 24, in <module>
  File "json/decoder.py", line 18, in _floatconstants
LookupError: unknown encoding: hex
Failed to execute script run
logout

**Now I have no idea... plz help!**

**Comment by SilicaAndPina** [comment]
try running from src.

do like 'python run.py'
u just need the requests and bplistlib module.

**Comment by SilicaAndPina** [comment]
PSVIMGTOOLS-FRONTEND is written in the latest python 2.7
and uses lots of things that will not work on python3.
also pyinstaller on mac hates anything but the one installed by default.
Just have you tried running it from src? 
just need requests and bplistlib
then run 'run.py'

**Comment by SilicaAndPina** [comment]
Development stopped.
