### ISSUE TITLE
psvimgtool 0.5.3 error

### ISSUE THREAD

**Issue by leo2997** [SilicaAndPina/psvimgtools-frontend#56]
hi im new to this stuff im trying to intall vhbl on my vita FW3.65 im using psvimgtool v0.5.3 i did all the other instructions on this site https://hackinformer.com/2017/04/28/psvita-install-vhbl-bubble-fw3-65/

but im getting an error when i press the easy installer
Exception in Tkinter callback
Traceback (most recent call last):
File "lib-tk\Tkinter.py", line 1541, in call
File "main_support.py", line 29, in esyInstall
File "C:\py64\Lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 396, in load_module
File "easyInstallers.py", line 18, in 
File "C:\py64\Lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 396, in load_module
File "easyInstallers_support.py", line 8, in 
ImportError: No module named easyinstallers.Whitelister.main

thank you i hope you can also help me

**Comment by BertrandLF** [comment]
+1

**Comment by Zenbabwei** [comment]
Hello I'm having the same error as leo2997 and I can't figure out what to do. How do you find the sources and add them to the folder manually? Any help would be greatly appreciated. Thanks Guys!

**Comment by Lowell009** [comment]
What Win are you running at...Because i am running win 8.1, 32 bit and i am getting the same problem

**Comment by leo2997** [comment]
I already fix using the lower version :)
