### ISSUE TITLE
Easy installer not starting

### ISSUE THREAD

**Issue by Lowell009** [SilicaAndPina/psvimgtools-frontend#57]
Hello...I am new to this stuff, but I have encountered a problem while trying to start "easy installers" it gives me this message:
Checking for updates
Latest Version Is: v0.5.3
Current Version Is: v0.5.3
No Updates Available.
Updating: C:\Users\Lowell\AppData\Roaming\psvimgtools-frontend/keydb.ini
Setting Up EasyInstallers.
Checking CMADir.txt
CHECK OK
Checking Account List
CHECK OK
Checking For 64-Bit
Running in 32-Bit mode.
Running OS Check
Test OK!, sys.platform: win32
Registering .cmbackup as a known filetype..
Executing: assoc .cmbackup=CmbackupFile
Access is denied.
Error occurred while processing: .cmbackup.
Executing: ftype CmbackupFile="C:\Users\Lowell\AppData\Roaming\psvimg
tools-frontend\run.exe"
Access is denied.
Error occurred while processing: CmbackupFile.
Starting GUI
Exception in Tkinter callback
Traceback (most recent call last):
 
 File "lib-tk\Tkinter.py", line 1541, in __call__
  File "main_support.py", line 29, in esyInstall
  File "C:\Python27\Lib\site-packages\PyInstaller\loader\pyimod03_importers.py",
 line 396, in load_module
  File "easyInstallers.py", line 18, in <module>
  File "C:\Python27\Lib\site-packages\PyInstaller\loader\pyimod03_importers.py",
 line 396, in load_module
  File "easyInstallers_support.py", line 8, in <module>
ImportError: No module named easyinstallers.Whitelister.main

i am running win 8.1, 32bits

**Comment by Nitrox14** [comment]
even I got the same issue

**Comment by SilicaAndPina** [comment]
i dont really know why this is happening
if you look here:
https://github.com/SilicaAndPina/psvimgtools-frontend/blob/master/easyinstallers/Whitelister/main.py
easyinstallers.Whitelister.main does exist.

**Comment by Olly213Gaming** [comment]
The same thing is happening to me , however , the folder is there with everything in it just PSVimgtools cant access or something.

 Exception in Tkinter callback
Traceback (most recent call last):

File "lib-tk\Tkinter.py", line 1541, in call
File "main_support.py", line 29, in esyInstall
File "C:\Python27\Lib\site-packages\PyInstaller\loader\pyimod03_importers.py",
line 396, in load_module
File "easyInstallers.py", line 18, in 
File "C:\Python27\Lib\site-packages\PyInstaller\loader\pyimod03_importers.py",
line 396, in load_module
File "easyInstallers_support.py", line 8, in 
ImportError: No module named easyinstallers.Whitelister.main

**Comment by SilicaAndPina** [comment]
mhm try the new update.
