### ISSUE TITLE
PSvimgtools crashing

### ISSUE THREAD

**Issue by Libor31** [SilicaAndPina/psvimgtools-frontend#64]
When i start, program crash....
Traceback (most recent call last):
  File "run.py", line 115, in <module>
  File "defs.py", line 360, in autoAccount
UnicodeDecodeError: 'ascii' codec can't decode byte 0xf8 in position 12: ordinal
 not in range(128)
[4528] Failed to execute script run

**Comment by SilicaAndPina** [comment]
Unicode characters in your username on windows?

**Comment by Libor31** [comment]
Dvořák

**Comment by Libor31** [comment]
yes

**Comment by SilicaAndPina** [comment]
it will be a pain to fix but ill try it in the next version.
until then just put it in a path that only uses ascii ..

**Comment by SilicaAndPina** [comment]
itll be a pain to fix, but ill try fix it wherever i messed it up. but there are alot of places >_>
