### ISSUE TITLE
Remove Featured is still not working for me on PSTV

### ISSUE THREAD

**Issue by the-importer** [SilicaAndPina/psvimgtools-frontend#68]
My firmware is now 3.67 and I've tried psvimgtools V0.5.4, but that annoying tab is still there :(

I get this when patching my backup BTW:
---------------------------------------------------------------------------------------------------------------
Executing: psvmd-decrypt.exe -K 65f40cdb6d5bf44bc6f93862836638038b082095928fbfb5a8f8dd15298c31c4 "D:/Backups/GameData Backup/Vita/Backups/SYSTEM/6dfef99edaf27d6b/201802102308-01/201802102308-01.psvmd" "D:/Backups/GameData Backup/Vita/Backups/EXTRACTED/SYSTEM/201802102308-01.psvmd-dec"
all done.
Copying File: D:/Backups/GameData Backup/Vita/Backups/SYSTEM/6dfef99edaf27d6b/201802102308-01/201802102308-01.psvinf To: D:/Backups/GameData Backup/Vita/Backups/EXTRACTED/SYSTEM/201802102308-01.psvinf
Patching With Featured App Removed!
Opening: D:/Backups/GameData Backup/Vita/Backups/EXTRACTED/SYSTEM/201802102308-01/ur0_shell/db/app.db
Executing DELETE FROM tbl_appinfo WHERE titleId='NPXS10102' AND val=0
DELETE FROM 'tbl_livearea' WHERE titleId='NPXS10102'
DELETE FROM 'tbl_livearea_frame' WHERE titleId='NPXS10102'
DELETE FROM tbl_appinfo WHERE titleId='NPXS10093' AND val=0
DELETE FROM 'tbl_livearea' WHERE titleId='NPXS10093'
DELETE FROM 'tbl_livearea_frame' WHERE titleId='NPXS10093'To app.db!
Exception in Tkinter callback
Traceback (most recent call last):
  File "lib-tk\Tkinter.py", line 1541, in __call__
  File "easyinstallers\RemoveFeatured\chooseBackup.py", line 134, in <lambda>
    self.Button1.configure(command = lambda: patch(self.backupList.get(ACTIVE)))
  File "easyinstallers\RemoveFeatured\chooseBackup.py", line 56, in patch
    appDatabase.executescript(sqlQuery)
OperationalError: near "DELETE": syntax error
---------------------------------------------------------------------------------------------------------------

**Comment by SilicaAndPina** [comment]
DELETE FROM tbl_appinfo WHERE titleId='NPXS10093' AND val=0 i probs messed this up.

**Comment by cdellosso3** [comment]
On firmware 3.68 I'm getting the same error. is there any update on this? thanks

**Comment by SilicaAndPina** [comment]
its getting mad because you had allready run this once, try rebuild the database and try again ..

**Comment by SilicaAndPina** [comment]
i acturaly have a vitatv now, so i may try messing with this.

**Comment by cdellosso3** [comment]
I tried rebuilding the database and creating a new backup afterwards but I still ran into the issue
