### ISSUE TITLE
Unable to Create Emububble as there are unsupported - MacOS

### ISSUE THREAD

**Issue by BOIBANCAN** [SilicaAndPina/psvimgtools-frontend#79]
Hi, I just got psvimgtools-frontend to run on my mac (by changing the run document file to a unix executable) and I wanted to install emulators on my ps vita. I used the psp/ps vita demo/game ape quest starter pack and installed VHBL, then I cloned it and tried to install emububbles. Unfortunately this came up.

Looking in: /Users/finsharking/Desktop/psvimgtools-frontend-macos/easyinstallers/EmuBubble/FILES
NesterJ 6da7c0360124896f NESTEREMU
Checking if allready extracted backup exists...
Exception in Tkinter callback
Traceback (most recent call last):
  File "lib-tk/Tkinter.py", line 1542, in __call__
  File "easyinstallers/EmuBubble/emububble.py", line 113, in <lambda>
    self.Button1.configure(command = lambda: emububble_support.createBackup(self.Scrolledlistbox1.get(ACTIVE),account,backup))
  File "easyinstallers/EmuBubble/emububble_support.py", line 15, in createBackup
    unsign_support.goUnsign(cmaBackup=backup,account=account,load="PGAME",resign=".")
  File "unsign_support.py", line 77, in goUnsign
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'

I'm not sure how to fix it and im also not sure if I need ape quest starter pack with no VHBL installed before cloning it. THANKS IN ADVANCE. (This worked fine on my windows laptop btw.)

**Comment by SilicaAndPina** [comment]
NoneType str, >_> i really hate this software ...

**Comment by BOIBANCAN** [comment]
so what should I do? Should I use a different psp demo/game.

**Comment by BOIBANCAN** [comment]
the set id I used was GBAEMULE1

**Comment by BOIBANCAN** [comment]
Should I change the type of emulator that im trying to install as a emububble (emulators are from GamersRebirthDL youtube channel).

**Comment by SilicaAndPina** [comment]
it could also mean *Somehow* load = NoneType buut im pretty sure i hardcoded it as PGAME on the emububbble shit. if your using a custom emulator. it could be the issue. . .

**Comment by BOIBANCAN** [comment]
Update: So i tried reinstalling psvimgtools and QCMA and left emulators by default to test them out. I can clone bubbles and install VHBL just fine, but i cannot install emububbles still. It gives the same result everytime. How do I solve load = NoneType.

**Comment by SilicaAndPina** [comment]
its probabaly some quirk with MacOS :d

**Comment by SilicaAndPina** [comment]
Oh. i totally forgot to mention, it could be that your CMA DIR is wrong. . i dont know how i didnt think of that xD
