### ISSUE TITLE
psvimgtools still won't start!

### ISSUE THREAD

**Issue by ABOhiccups** [SilicaAndPina/psvimgtools-frontend#87]
I try to run psvimgtools on Windows 10. It won't start. I also did try to install psvimgtools. It also won't start after it finish installing. I also update psvimgtools and it still won't start after updating.

I try to open on Linux. Same thing. It won't start.

**Comment by ABOhiccups** [comment]
Here's a screenshot from Windows 10.
![run_2018-05-22_21-54-25](https://user-images.githubusercontent.com/17691106/40399352-e8097154-5e0a-11e8-81c6-3a54e717aa0d.png)

**Comment by ABOhiccups** [comment]
Here's one from Linux Version.

`Traceback (most recent call last):
  File "run.py", line 2, in <module>
  File "/usr/local/lib/python2.7/dist-packages/PyInstaller/loader/pyimod03_importers.py", line 396, in load_module
  File "defs.py", line 418, in <module>
  File "/usr/local/lib/python2.7/dist-packages/PyInstaller/loader/pyimod03_importers.py", line 396, in load_module
  File "accSelect_support.py", line 2, in <module>
  File "/usr/local/lib/python2.7/dist-packages/PyInstaller/loader/pyimod03_importers.py", line 396, in load_module
  File "backupType_support.py", line 6, in <module>
  File "/usr/local/lib/python2.7/dist-packages/PyInstaller/loader/pyimod03_importers.py", line 396, in load_module
  File "sign.py", line 7, in <module>
ImportError: No module named pfs
[5149] Failed to execute script run`

**Comment by ABOhiccups** [comment]
Here's another screenshot from Linux.

![screenshot_2018-05-22_23-17-05](https://user-images.githubusercontent.com/17691106/40401901-e3b41422-5e16-11e8-84b3-87b828b54bdc.png)

**Comment by SilicaAndPina** [comment]
'no module named pfs' dafuck ? *either currupt file or its arch'es fault*'

from windows 10 i dont see any errors at all xD whats the problem ?

**Comment by ABOhiccups** [comment]
Problem solved on Windows Version. You have to have QCMA or Official Sony Content Manager installed in order to use psvimgtools on Windows.

**Comment by SilicaAndPina** [comment]
No Shit sherlock
